/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import DTO.ThongTinLo;
import DAO.dLoSanPham;
import DAO.dPhieuXuat;
import DAO.dSanPham;
import DTO.CTLoSanPham;
import DTO.ChonSPTra;
import DTO.LoSanPham;
import DTO.SanPham;
import DTO.ThongTinSPHienCo;
import DTO.ThongTinXuat;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author P50
 */
public class ChonSanPhamXuat extends javax.swing.JFrame {

    /**
     * Creates new form ChonSanPham
     */
    public int ID_Nv;


    public ChonSanPhamXuat() {
    }
    
    
    public ChonSanPhamXuat(int ID_Nv) {
        initComponents();
        setLocationRelativeTo(null);
        this.ID_Nv = ID_Nv;
        build();
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JScrollPane = new javax.swing.JScrollPane();
        tbchon = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        btntieptuc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(64, 128, 186));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Chọn Sản Phẩm");

        tbchon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Tên Sản Phẩm", "Số Lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbchon.setRowHeight(30);
        tbchon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbchonMouseClicked(evt);
            }
        });
        JScrollPane.setViewportView(tbchon);

        jButton1.setText("Tìm Kiếm");

        btntieptuc.setText("Tiếp Tục");
        btntieptuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntieptucActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(191, 191, 191))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btntieptuc)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btntieptuc)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
        public void build() {
       
        listDanhSachSanPham();
        

    }
    public void listDanhSachSanPham() {
//        DefaultTableModel model = (DefaultTableModel) tbchon.getModel();
//        while (tbchon.getRowCount() > 0) {
//            model.removeRow(0);
//        }
//        ArrayList<ThongTinSPHienCo> arr = dSanPham.getInstance().getListThongTinSPHienCo();
//        arr.stream().forEach((item) -> {
//            model.addRow(new Object[]{item.ID_Lo_Sp, item.Ten_Sp, item.So_Luong_Lo});
//        });
DefaultTableModel model = (DefaultTableModel) tbchon.getModel();
        while (tbchon.getRowCount() > 0) {
            model.removeRow(0);
        }
        
        // code của Tiến
//        ArrayList<Kho> arr = DAO.daoKho.getInstance().getListKho();
//        arr.stream().forEach((item) -> {
//            //System.out.print(item.id_lo_sp);
//            ChiTietLoSanPham ctlsp = DAO.daoChiTietLoSanPham.getInstance().getChiTietLoSanPham(item.id_lo_sp);
//            SanPham sp = DAO.daoSanPham.getInstance().getSanPham(ctlsp.id_sp);
//            LoSanPham lsp = DAO.daoLoSanPham.getInstance().getLoSanPham(item.id_lo_sp);
//            PhieuNhap pn = DAO.daoPhieuNhap.getInstance().getPhieuNhap(lsp.id_phieu_nhap);
//            ChiTietPhieuNhap ctpn = DAO.daoChiTietPhieuNhap.getInstance().getChiTietPhieuNhap(pn.id_phieu_nhap);
//            NguonCungCap ncc = DAO.daoNguonCungCap.getInstance().getNguonCungCap(ctpn.id_nguon_cc);
//            model.addRow(new Object[]{item.id_lo_sp, ncc.ten_nha_cc, sp.ten_sp, item.sl_san_pham});
//        });
           ArrayList<ChonSPTra> arr  = DAO.dLoSanPham.getInstance().getListSPTra();
           arr.stream().forEach((item) -> {
               model.addRow(new Object[]{item.ID_Lo_Sp, item.Ten_Sp, item.So_Luong_Sp});
           });
    }
//    public void listDanhSachSanPham(ArrayList<ThongTinSPHienCo> arr) {
//        DefaultTableModel model = (DefaultTableModel) tbchon.getModel();
//        while (tbchon.getRowCount() > 0) {
//            model.removeRow(0);
//        }
//        arr.stream().forEach((item) -> {
//          
//            model.addRow(new Object[]{item.ID_Lo_Sp, item.Ten_Sp, item.So_Luong_Lo});
//        });
//    }
    
    private void btntieptucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntieptucActionPerformed
           // TODO add your handling code here:
//           if (TaoPhieuXuat.checkOpen()) {
//            dispose();
//        } else {
//            ThongTinLo lo = new ThongTinLo();
//            
//            int selectrow = tbchon.getSelectedRow();
//            String id_lo = tbchon.getValueAt(selectrow, 0).toString();
//            String tensp = tbchon.getValueAt(selectrow, 1).toString();
//            String sl = tbchon.getValueAt(selectrow, 2).toString();
//            System.out.println(tensp);
//             lo = dLoSanPham.getInstance().getThongTinLo(Integer.parseInt(id_lo));
//            
//            
//
//            CTLoSanPham ctlsp = DAO.dCTLoSanPham.getInstance().getChiTietLoSanPham(Integer.parseInt(id_lo));
//            SanPham sp = DAO.dSanPham.getInstance().getSanPham(ctlsp.ID_Sp);
//            LoSanPham lsp = DAO.dLoSanPham.getInstance().getLoSanPham(Integer.parseInt(id_lo));
//            String NSX = lsp.NSX;
//            String HSD = lsp.HSD;
//            String loaisp = DAO.dLoaiSanPham.getInstance().getLoaiSanPham(sp.ID_Loai_Sp).Ten_Loai_Sp;
//
//            JFrame XuatKho = new TaoPhieuXuat(ID_Nv, 1);
//            XuatKho.setVisible(false);
//            //ThongTinSPHienCo item = DAO.dSanPham.getInstance().getThongTinSPHienCo(Integer.parseInt(id_lo));
//            TaoPhieuXuat.getInstance().setText(lo.Ten_Sp, lo.HSD,sl, lo.NSX,lo.Ten_Loai_Sp, id_lo);
//            dispose();
//        //}

        int selectrow = tbchon.getSelectedRow();
        String id_lo = tbchon.getValueAt(selectrow, 0).toString();
        LoSanPham kho = DAO.dLoSanPham.getInstance().getLoSanPham(Integer.parseInt(id_lo));
        //NhanVien nv = DAO.DangNhap.getInstance().getNhanVien(ID_Nv);
        JFrame TraHang = new TaoPhieuXuat(ID_Nv,kho.ID_Lo_Sp);
        TraHang.setVisible(true);
        dispose();
    }//GEN-LAST:event_btntieptucActionPerformed

    private void tbchonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbchonMouseClicked
        // TODO add your handling code here:
//        int selectrow = tbchon.getSelectedRow();
//        String id_lo = tbchon.getValueAt(selectrow, 0).toString();
//        String tensp = tbchon.getValueAt(selectrow, 1).toString();
//        String sl = tbchon.getValueAt(selectrow, 2).toString();
//
//        CTLoSanPham ctlsp = DAO.dCTLoSanPham.getInstance().getChiTietLoSanPham(Integer.parseInt(id_lo));
//        SanPham sp = DAO.dSanPham.getInstance().getSanPham(ctlsp.ID_Sp);
//        LoSanPham lsp = DAO.dLoSanPham.getInstance().getLoSanPham(Integer.parseInt(id_lo));
//        String NSX = lsp.NSX;
//        String HSD = lsp.HSD;
//        String loaisp = DAO.dLoaiSanPham.getInstance().getLoaiSanPham(sp.ID_Loai_Sp).Ten_Loai_Sp;
//        TaoPhieuXuat.getInstance().setText(tensp, HSD, sl, NSX,loaisp, id_lo);
    }//GEN-LAST:event_tbchonMouseClicked

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongTinSPHienCo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongTinSPHienCo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongTinSPHienCo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongTinSPHienCo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChonSanPhamXuat(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPane;
    private javax.swing.JButton btntieptuc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tbchon;
    // End of variables declaration//GEN-END:variables
}
