/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DTO.CTLoSanPham;

import DTO.LoSanPham;
import DTO.LoaiSanPham;
import DTO.NhanVien;
import DTO.SanPham;
import DTO.TaiKhoan;
import DTO.XuatKho;


/**
 *
 * @author Dinh Tien
 */
public class CTPhieuXuat extends javax.swing.JFrame {

    /**
     * Creates new form fPrintPhieuXuat
     */
    public int id_nv;
    public int id_px;
    public CTPhieuXuat() {
        initComponents();

    }
    public CTPhieuXuat(int id_nv, int id_px)
    {
        this.id_nv=id_nv;
        this.id_px=id_px;
        initComponents();
        build();
    }

    public void build()
    {
        ThongTinIn();
    }
    public void ThongTinIn()
    {
        XuatKho px = DAO.dPhieuXuat.getInstance().getPXuatKho(id_px);
        NhanVien nv = DAO.DangNhap.getInstance().getNhanVien(px.ID_Nv);
        TaiKhoan tk = DAO.DangNhap.getInstance().getTaiKhoan(id_nv);
        CTLoSanPham lsp = DAO.dCTLoSanPham.getInstance().getChiTietLoSanPham(px.ID_Lo_Sp);
        SanPham sp = DAO.dSanPham.getInstance().getSanPham(lsp.ID_Sp);
//        LoaiSanPham loaisp = DAO.dLoaiSanPham.getInstance().getLoaiSanPham(sp.ID_Loai_Sp);
        
       lbnv.setText(nv.Ten_Nv);
//        if (tk.Loai==1)
//            lbbophan.setText("Quản lý");
//        if (tk.Loai==2)
//            lbbophan.setText("Nhập kho");
//        if (tk.Loai==3)
            lbbophan.setText("Xuất kho");
        lbnx.setText(px.Thoi_Gian_Xuat);
        lblo.setText(String.valueOf(px.ID_Lo_Sp));
        lbtensp.setText(sp.Ten_Sp);
        lbsoluong.setText(String.valueOf(px.SL_Sp));
        lbdonvi.setText(sp.Don_Vi);
        lbdongia.setText(String.valueOf(lsp.So_Tien_Sp));
        lbidxuat.setText(String.valueOf(px.ID_Xuat_Kho));

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbnv = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbbophan = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbnx = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbidxuat = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbtensp = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbdonvi = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbdongia = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbsoluong = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(64, 128, 186));

        jPanel3.setBackground(new java.awt.Color(2, 84, 164));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Hệ Thống Quản Lý Kho");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Siêu Thị IT2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nhân Viên Phụ Trách: ");

        lbnv.setForeground(new java.awt.Color(255, 255, 255));
        lbnv.setText("jLabel4");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Bộ Phận: ");

        lbbophan.setForeground(new java.awt.Color(255, 255, 255));
        lbbophan.setText("jLabel7");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ngày Xuất: ");

        lbnx.setForeground(new java.awt.Color(255, 255, 255));
        lbnx.setText("jLabel8");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID Xuất");

        lbidxuat.setForeground(new java.awt.Color(255, 255, 255));
        lbidxuat.setText("jLabel2");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Mã Lô:");

        lblo.setForeground(new java.awt.Color(255, 255, 255));
        lblo.setText("jLabel9");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tên Sản Phẩm:");

        lbtensp.setForeground(new java.awt.Color(255, 255, 255));
        lbtensp.setText("jLabel10");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Đơn Vị:");

        lbdonvi.setForeground(new java.awt.Color(255, 255, 255));
        lbdonvi.setText("jLabel11");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Đơn Gía");

        lbdongia.setForeground(new java.awt.Color(255, 255, 255));
        lbdongia.setText("jLabel12");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Số Lượng Xuất: ");

        lbsoluong.setForeground(new java.awt.Color(255, 255, 255));
        lbsoluong.setText("jLabel13");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbnv, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbidxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbtensp, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(46, 46, 46)
                                .addComponent(lbbophan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbnx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbdonvi, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                    .addComponent(lbdongia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jLabel12)
                        .addGap(41, 41, 41)
                        .addComponent(lbsoluong)))
                .addContainerGap(67, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbnv)
                    .addComponent(jLabel6)
                    .addComponent(lbbophan))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbnx)
                    .addComponent(jLabel1)
                    .addComponent(lbidxuat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblo)
                    .addComponent(jLabel10)
                    .addComponent(lbdonvi))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lbtensp)
                    .addComponent(jLabel11)
                    .addComponent(lbdongia))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lbsoluong))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CTPhieuXuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CTPhieuXuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CTPhieuXuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CTPhieuXuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CTPhieuXuat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbbophan;
    private javax.swing.JLabel lbdongia;
    private javax.swing.JLabel lbdonvi;
    private javax.swing.JLabel lbidxuat;
    private javax.swing.JLabel lblo;
    private javax.swing.JLabel lbnv;
    private javax.swing.JLabel lbnx;
    private javax.swing.JLabel lbsoluong;
    private javax.swing.JLabel lbtensp;
    // End of variables declaration//GEN-END:variables
}
